// Generated by CoffeeScript 1.4.0
(function() {
  var $document;

  $document = $(document);

  $document.on('tap', '#test-tap', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('taphold', '#test-taphold', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('swipeleft', '#test-swipeleft', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('swiperight', '#test-swiperight', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('swipe', '#test-swipe', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('vmouseout', '#test-vmouseout', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('vmouseover', '#test-vmouseover', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('vmousedown', '#test-vmousedown', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('vmousemove', '#test-vmousemove', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('vmouseup', '#test-vmouseup', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('vmousecancel', '#test-vmousecancel', function(e) {
    return $(this).toggleClass('toggled');
  });

  $document.on('vclick', '#test-vclick', function(e) {
    return $(this).toggleClass('toggled');
  });

  $(function() {
    (function() {
      var $occured, $orientation, count;
      count = 0;
      $occured = $('#test-orientationchange-occured');
      $orientation = $('#test-orientationchange-orientation');
      return $document.on('orientationchange', function(e) {
        count += 1;
        $occured.text(count);
        return $orientation.text(e.orientation);
      });
    })();
    return (function() {
      var $result;
      $result = $('#test-scrollstartstop');
      $document.on('scrollstart', function(e) {
        $result.text('scrollstart occured.');
        return $result.toggleClass('toggled');
      });
      return $document.on('scrollstop', function(e) {
        $result.text('scrollstop occured.');
        return $result.toggleClass('toggled');
      });
    })();
  });

}).call(this);
