// Generated by CoffeeScript 1.4.0
(function() {
  var $document;

  $document = $(document);

  $document.on('pagebeforeload', function() {
    return console.log('pagebeforeload');
  });

  $document.on('pageload', function() {
    return console.log('pageload');
  });

  $document.on('pageloadfailed', function() {
    return console.log('pageloadfailed');
  });

  $document.on('pagebeforechange', function() {
    return console.log('pagebeforechange');
  });

  $document.on('pagechange', function() {
    return console.log('pagechange');
  });

  $document.on('pagechangefailed', function() {
    return console.log('pagechangefailed');
  });

  $document.on('pagebeforeshow', function() {
    return console.log('pagebeforeshow');
  });

  $document.on('pagebeforehide', function() {
    return console.log('pagebeforehide');
  });

  $document.on('pageshow', function() {
    return console.log('pageshow');
  });

  $document.on('pagehide', function() {
    return console.log('pagehide');
  });

  $document.on('pagebeforecreate', function() {
    return console.log('pagebeforecreate');
  });

  $document.on('pagecreate', function() {
    return console.log('pagecreate');
  });

  $document.on('pageinit', function() {
    return console.log('pageinit');
  });

  $document.on('pageremove', function() {
    return console.log('pageremove');
  });

  $document.on('updatelayout', function() {
    return console.log('updatelayout');
  });

  $document.on('pagehide', function(e, ui) {
    return $(ui.nextPage).animationComplete(function() {
      return console.log('pagehide animation complete');
    });
  });

  $document.on('click', '#example1', function() {
    return $.mobile.changePage('2.html');
  });

  $document.on('click', '#example2', function() {
    return $.mobile.changePage('2.html', {
      transition: 'slideup'
    });
  });

  $document.on('click', '#example3', function() {
    return $.mobile.changePage('2.html', {
      type: 'post'
    });
  });

  $document.on('click', '#example4', function() {
    return $.mobile.changePage('2.html', {
      reloadPage: true
    });
  });

}).call(this);
